server:
  port: 8040
  context-path: /backoffice-bff

spring:
  application:
    name: backoffice-bff
  profiles:
    active: prod
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://identity:8080/realms/CourseRealm}
        registration:
          keycloak:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: ${KEYCLOAK_CLIENT_SECRET_BACKOFFICE:hgDVSKURLE6VUsHT09AaZ3YlhYRy1JsF}
            scope: openid, profile, email, roles

---
spring:
  config:
    active:
      on-profile: "prod"
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: api
          uri: http://api.hajime.local
          predicates:
            - Path=/api/*
          filters:
            - TokenRelay
            - StripPrefix=1
---

service-uri:
  services:
    user-service: ${USER_SERVICE_URI:http://localhost:9000}
    course-service: ${COURSE_SERVICE_URI:http://localhost:9002}
    token-identity: ${KEYCLOAK_TOKEN_URI:http://localhost:8080/realms/CourseRealm/protocol/openid-connect/token}
  token-id: storefront-bff
  token-secret: ${KEYCLOAK_CLIENT_SECRET_STOREFRONT:XljBWoGzc215LCKgNp7Ml5BgjQPJam3W}